#pragma once

void PowerA3(double& a, double& b);
void PowerA234(double& a, double& b, double& c, double& d);
void Mean(double& x, double& y, double& amean, double& gmean);
void TrianglePS(double& a, double& p, double& s);
void RectPS(int& x1, int& y1, int& x2, int& y2, double& p, double& s);
void DigitCountSum(int& k, int& c, int& s);
void InvDigits(int& k);
void AddRightDigit(int& d, int& k);
void AddLeftDigit(int& d, int& k);
void Swap(int& x, int& y);
void Minmax(int& x, int& y);
void SortInc3(int& a, int& b, int& c);
void SortDec3(int& a, int& b, int& c);
void ShiftRight3(int& a, int& b, int& c);
void ShiftLeft3(int& a, int& b, int& c);
int Sign(double& x);
int RootCount(double& a, double& b, double& c);
double CircleS(double& r);
double RingS(double& r1, double& r2);
double TriangleP(double& a, double& h);
int SumRange(int& a, int& b);
double Calc(double& a, double& b, int& op);
int Quarter(double& x, double& y);
bool Even(int& k);
bool IsSquare(int& k);
bool IsPower5(int& k);
bool IsPowerN(int& k, int& n);
bool IsPrime(int& n);
int DigitCount(int& k);
int DigitN(int& k, int& n);
bool IsPalindrome(int& k);
double DegToRad(double& d);
double RadToDeg(double& d);
double Fact(int& n);
double Fact2(int& n);
int Fib(int& n);
double Power1(double& a, double& b);
double Power2(double& a, int& n);
double Power3(double& a, double& b);
double Exp1(double& x, double& e);
double Sin1(double& x, double& e);
double Cos1(double& x, double& e);
double Ln1(double& x, double& e);
double Arctg1(double& x, double& e);
double Power4(double& x, double& a, double& e);
int GCD2(int& a, int& b);
void Frac1(int& a, int& b, int& p, int& q);
int LCM2(int& a, int& b);
int GCD3(int& a, int& b, int& c);
void TimeToHMS(int& h, int& m, int& s, int& t);
void IncTime(int& h, int& m, int& s, int& t);
bool IsLeapYear(int& y);
int MonthDays(int& m, int& y);
void PrevDate(int& d, int& m, int& y);
void NextDate(int& d, int& m, int& y);
double Leng(double& xa, double& ya, double& xb, double& yb);
double Perim(double& xa, double& ya, double& xb, double& yb, double& xc, double& yc);
double Area(double& xa, double& ya, double& xb, double& yb, double& xc, double& yc);
double Dist(double& xp, double& yp, double& xa, double& ya, double& xb, double& yb);
void Altitudes(double& xa, double& ya, double& xb, double& yb, double& xc, double& yc, double& ha, double& hb, double& hc);